---
title: "SegBo: basic descriptive stats"
author: "Steven Moran"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  github_document:
  pandoc_args: --webtex
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE, include=FALSE}
library(dplyr)
library(knitr)
```

```{r}
# Load the data
segbo <- read.csv('../../data/segbo_with_glottolog.csv')
```

```{r}
# Number of observations, i.e. number of borrowed sounds across the languages in SegBo
kable(head(segbo %>% select(LanguageName, BorrowedSound) %>% distinct()))
nrow(segbo %>% select(LanguageName, BorrowedSound) %>% distinct())
```

```{r}
# Number of distinct donor languages or dialects (via Glottocodes)
kable(head(segbo %>% select(SourceLanguageGlottocode) %>% distinct()))
nrow(segbo %>% select(SourceLanguageGlottocode) %>% distinct())
```

```{r}
# Number of distinct borrowing languages or dialects (via Glottocodes)
kable(head(segbo %>% select(BorrowingLanguageGlottocode) %>% distinct()))
nrow(segbo %>% select(BorrowingLanguageGlottocode) %>% distinct())
```

```{r}
# Number of distinct borrowing languages (as marked via ISO 639-3 codes)
kable(head(segbo %>% select(iso639P3code) %>% distinct()))
nrow(segbo %>% select(iso639P3code) %>% distinct())
```



```{r}
# Number of families for borrowing languages (note the empty field because we don't know for many data points where the sound was borrowed from)
x <- segbo %>% select(SourceLanguageGlottocode, family_id)
y <- x %>% group_by(family_id) %>% summarize(count=n())
kable(head(y))
nrow(y)
```

```{r}
# And number of families for source languages -- this isn't going to work now because the language family is tied to the BorrowingLanguage...
x <- segbo %>% select(LanguageName, family_id)
y <- x %>% group_by(family_id) %>% summarize(count=n())
kable(head(y))
nrow(y)
```

