---
title: "Merge SegBo Phoneme and Metadata tables"
author: "Steven Moran"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  github_document:
  pandoc_args: --webtex
---
  
```{r, echo=FALSE, include=FALSE}
library(dplyr)
library(testthat)
```

```{r}
# Load SegBo CSV dumps from Google sheets
segbo.phonemes <- read.csv('../data/SegBo database - Phonemes.csv', na.strings = "", stringsAsFactors = FALSE)
segbo.metadata <- read.csv('../data/SegBo database - Metadata.csv', na.strings = "", stringsAsFactors = FALSE)
```

```{r}
df <- left_join(segbo.phonemes, segbo.metadata, by=c("InventoryID"="InventoryID"))
glimpse(df)
```

```{r}
# Test that all of the Glottocodes match
expect_equal(nrow(df[which(df$Glottocode!=df$BorrowingLanguageGlottocode),] %>% select(InventoryID, BorrowingLanguageGlottocode, Glottocode, LanguageName, LanguageName)), 0)
```

```{r}
# Test that all of the language names match
expect_equal(nrow(df[which(df$LanguageName!=df$BorrowingLanguageName),] %>% select(InventoryID, LanguageName, LanguageName)), 0)
```

```{r}
# Test for any NA Glottocodes? in the BorrowingLanguageGlottocode field
expect_false(any(is.na(df$BorrowingLanguageGlottocode)))
```

```{r}
# Write full table to disk
write.csv(df, file='../data/segbo_merged.csv', row.names = F)
```
